購入履歴画面と購入明細画面を実装しました。#14
chika-O/lamp_practice pull request #15
Opened 2021-04-16 06:15 UTC by chika-O

@primestyleus 
ご確認をお願いいたします。

2021-04-16 14:04 UTC, primestyleus requested changes
@chika-O 
実装おつかれさまでした。1点だけうまくできていない点をコメントしましたので、ご確認と修正をお願いします。

2021-04-16 14:04 UTC, primestyleus commented on www/html/purchase_details.php
> +if(($data['user_id'] !== $user['user_id']) && (is_admin($user) === false)) {
get_purchase_historyでfetchではなくfetch_allを使っているので、$data['user_id']ではなく$data[0]['user_id']になると思います。もしくは関数のほうをfetchにかえて、Viewのほうも変更頂く形になります。

2021-04-17 05:32 UTC, chika-O commented
@primestyleus 
ご指摘いただいていた箇所への修正を加えましたので、ご確認をお願いいたします。

2021-04-17 11:51 UTC, primestyleus approved these changes
@chika-O 修正ありがとうございます。マージします。

2021-04-17 11:51 UTC, merged